[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  PDF_FONT_ARIAL_PATH = "fonts/Arial.ttf"
  PDF_FONT_ARIAL_BOLD_PATH = "fonts/Arial-Bold.ttf"
  PDF_FONT_CALIBRI_PATH = "fonts/Calibri.ttf"

[[plugins]]
  package = "@netlify/plugin-nextjs"
